version: 0.0.{build}
before_build:
- cmd: nuget restore hMoney.sln
- choco install opencover.portable
- choco install codecov
build:
  verbosity: minimal
test_script:
- cmd: >-
    nuget install Appveyor.TestLogger -Version 2.0.0
    
    dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor hMoney.sln
    
    dir
    
    dir hMoneyVSTests
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\hMoneyVSTests\bin\Debug\net5.0-windows\hMoneyVSTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[hMoneyVSTests*]*" -output:".\hMoney_coverage.xml"

- codecov -f "hMoney_coverage.xml"
artifacts:
- path: hMoney
  name: hMoney.exe
