version: 0.0.{build}
before_build:
- cmd: nuget restore hMoney.sln
build:
  verbosity: minimal
test_script:
- cmd: >-
    nuget install Appveyor.TestLogger -Version 2.0.0

    dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor hMoney.sln
artifacts:
- path: hMoney
  name: hMoney.exe
