//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hMoney {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormMain() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hMoney.FormMain", typeof(FormMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 False 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool aboutToolStripMenuItem_Enabled {
            get {
                object obj = ResourceManager.GetObject("aboutToolStripMenuItem.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=154, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size aboutToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("aboutToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Check &amp;Update 的當地語系化字串。
        /// </summary>
        internal static string aboutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=178,Y=4} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point btnRefreshForecast_Location {
            get {
                object obj = ResourceManager.GetObject("btnRefreshForecast.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding btnRefreshForecast_Margin {
            get {
                object obj = ResourceManager.GetObject("btnRefreshForecast.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=80, Height=25} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size btnRefreshForecast_Size {
            get {
                object obj = ResourceManager.GetObject("btnRefreshForecast.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int btnRefreshForecast_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnRefreshForecast.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Refresh 的當地語系化字串。
        /// </summary>
        internal static string btnRefreshForecast_Text {
            get {
                return ResourceManager.GetString("btnRefreshForecast.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=154, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size cCToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("cCToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;About 的當地語系化字串。
        /// </summary>
        internal static string cCToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cCToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string ColumnAccount_HeaderText {
            get {
                return ResourceManager.GetString("ColumnAccount.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnAccount_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnAccount.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountId 的當地語系化字串。
        /// </summary>
        internal static string ColumnAccountId_HeaderText {
            get {
                return ResourceManager.GetString("ColumnAccountId.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnAccountId_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnAccountId.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 False 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnAccountId_Visible {
            get {
                object obj = ResourceManager.GetObject("ColumnAccountId.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountName 的當地語系化字串。
        /// </summary>
        internal static string ColumnAccountName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnAccountName.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnAccountName_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnAccountName.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 250 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int ColumnAccountName_Width {
            get {
                object obj = ResourceManager.GetObject("ColumnAccountName.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Balance 的當地語系化字串。
        /// </summary>
        internal static string ColumnBalance_HeaderText {
            get {
                return ResourceManager.GetString("ColumnBalance.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnBalance_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnBalance.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Category 的當地語系化字串。
        /// </summary>
        internal static string ColumnCategory_HeaderText {
            get {
                return ResourceManager.GetString("ColumnCategory.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnCategory_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnCategory.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Date 的當地語系化字串。
        /// </summary>
        internal static string ColumnDate_HeaderText {
            get {
                return ResourceManager.GetString("ColumnDate.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnDate_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnDate.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Expense 的當地語系化字串。
        /// </summary>
        internal static string ColumnExpense_HeaderText {
            get {
                return ResourceManager.GetString("ColumnExpense.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnExpense_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnExpense.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountId 的當地語系化字串。
        /// </summary>
        internal static string ColumnForecastAccountId_HeaderText {
            get {
                return ResourceManager.GetString("ColumnForecastAccountId.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnForecastAccountId_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnForecastAccountId.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 False 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnForecastAccountId_Visible {
            get {
                object obj = ResourceManager.GetObject("ColumnForecastAccountId.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 AccountName 的當地語系化字串。
        /// </summary>
        internal static string ColumnForecastAccountName_HeaderText {
            get {
                return ResourceManager.GetString("ColumnForecastAccountName.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnForecastAccountName_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnForecastAccountName.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 250 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int ColumnForecastAccountName_Width {
            get {
                object obj = ResourceManager.GetObject("ColumnForecastAccountName.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Reconciled 的當地語系化字串。
        /// </summary>
        internal static string ColumnForecastReconciled_HeaderText {
            get {
                return ResourceManager.GetString("ColumnForecastReconciled.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnForecastReconciled_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnForecastReconciled.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Today 的當地語系化字串。
        /// </summary>
        internal static string ColumnForecastToday_HeaderText {
            get {
                return ResourceManager.GetString("ColumnForecastToday.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnForecastToday_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnForecastToday.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Future 的當地語系化字串。
        /// </summary>
        internal static string ColumnFuture_HeaderText {
            get {
                return ResourceManager.GetString("ColumnFuture.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnFuture_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnFuture.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Income 的當地語系化字串。
        /// </summary>
        internal static string ColumnIncome_HeaderText {
            get {
                return ResourceManager.GetString("ColumnIncome.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnIncome_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnIncome.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Notes 的當地語系化字串。
        /// </summary>
        internal static string ColumnNotes_HeaderText {
            get {
                return ResourceManager.GetString("ColumnNotes.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnNotes_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnNotes.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Payee 的當地語系化字串。
        /// </summary>
        internal static string ColumnPayee_HeaderText {
            get {
                return ResourceManager.GetString("ColumnPayee.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnPayee_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnPayee.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Reconciled 的當地語系化字串。
        /// </summary>
        internal static string ColumnReconciled_HeaderText {
            get {
                return ResourceManager.GetString("ColumnReconciled.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnReconciled_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnReconciled.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        internal static string ColumnStatus_HeaderText {
            get {
                return ResourceManager.GetString("ColumnStatus.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnStatus_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnStatus.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Today 的當地語系化字串。
        /// </summary>
        internal static string ColumnToday_HeaderText {
            get {
                return ResourceManager.GetString("ColumnToday.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool ColumnToday_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("ColumnToday.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=67, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size englishToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("englishToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=135, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size exitToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("exitToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 E&amp;xit 的當地語系化字串。
        /// </summary>
        internal static string exitToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=38, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size fileToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("fileToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;File 的當地語系化字串。
        /// </summary>
        internal static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle gridForecast_Dock {
            get {
                object obj = ResourceManager.GetObject("gridForecast.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point gridForecast_Location {
            get {
                object obj = ResourceManager.GetObject("gridForecast.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding gridForecast_Margin {
            get {
                object obj = ResourceManager.GetObject("gridForecast.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1042, Height=587} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size gridForecast_Size {
            get {
                object obj = ResourceManager.GetObject("gridForecast.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int gridForecast_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gridForecast.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point gridSummary_Location {
            get {
                object obj = ResourceManager.GetObject("gridSummary.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding gridSummary_Margin {
            get {
                object obj = ResourceManager.GetObject("gridSummary.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 None 的類型 System.Windows.Forms.ScrollBars 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.ScrollBars gridSummary_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("gridSummary.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.ScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=646, Height=1864} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size gridSummary_Size {
            get {
                object obj = ResourceManager.GetObject("gridSummary.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int gridSummary_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gridSummary.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle gridTrans_Dock {
            get {
                object obj = ResourceManager.GetObject("gridTrans.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=4,Y=4} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point gridTrans_Location {
            get {
                object obj = ResourceManager.GetObject("gridTrans.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding gridTrans_Margin {
            get {
                object obj = ResourceManager.GetObject("gridTrans.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 22 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int gridTrans_RowHeadersWidth {
            get {
                object obj = ResourceManager.GetObject("gridTrans.RowHeadersWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1042, Height=610} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size gridTrans_Size {
            get {
                object obj = ResourceManager.GetObject("gridTrans.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int gridTrans_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gridTrans.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=22,Y=9} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=0,Right=4,Bottom=0} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding label1_Margin {
            get {
                object obj = ResourceManager.GetObject("label1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=97, Height=15} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Forecast month: 的當地語系化字串。
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=136, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size languagesToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("languagesToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Languages 的當地語系化字串。
        /// </summary>
        internal static string languagesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("languagesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point menuStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=7,Top=2,Right=0,Bottom=2} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding menuStrip1_Padding {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1281, Height=24} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size menuStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int menuStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 menuStrip1 的當地語系化字串。
        /// </summary>
        internal static string menuStrip1_Text {
            get {
                return ResourceManager.GetString("menuStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=137,Y=17} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=135, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size openFileToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("openFileToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Open file... 的當地語系化字串。
        /// </summary>
        internal static string openFileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openFileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=136, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size optionsToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("optionsToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Options 的當地語系化字串。
        /// </summary>
        internal static string optionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle panelForecast_Dock {
            get {
                object obj = ResourceManager.GetObject("panelForecast.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=4,Y=39} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point panelForecast_Location {
            get {
                object obj = ResourceManager.GetObject("panelForecast.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding panelForecast_Margin {
            get {
                object obj = ResourceManager.GetObject("panelForecast.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1042, Height=587} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size panelForecast_Size {
            get {
                object obj = ResourceManager.GetObject("panelForecast.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 3 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int panelForecast_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panelForecast.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Top 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle panelForecastHeader_Dock {
            get {
                object obj = ResourceManager.GetObject("panelForecastHeader.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=4,Y=4} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point panelForecastHeader_Location {
            get {
                object obj = ResourceManager.GetObject("panelForecastHeader.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding panelForecastHeader_Margin {
            get {
                object obj = ResourceManager.GetObject("panelForecastHeader.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1042, Height=35} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size panelForecastHeader_Size {
            get {
                object obj = ResourceManager.GetObject("panelForecastHeader.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int panelForecastHeader_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panelForecastHeader.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=46, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size qqToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("qqToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Help 的當地語系化字串。
        /// </summary>
        internal static string qqToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("qqToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle splitContainer1_Dock {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=24} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point splitContainer1_Location {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding splitContainer1_Margin {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1281, Height=658} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size splitContainer1_Size {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 218 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int splitContainer1_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 5 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int splitContainer1_SplitterWidth {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.SplitterWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 8 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int splitContainer1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=682} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point statusStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=1,Top=0,Right=16,Bottom=0} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding statusStrip1_Padding {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1281, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size statusStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int statusStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 statusStrip1 的當地語系化字串。
        /// </summary>
        internal static string statusStrip1_Text {
            get {
                return ResourceManager.GetString("statusStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=17,Y=17} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point statusStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=4,Y=24} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point tabAccount_Location {
            get {
                object obj = ResourceManager.GetObject("tabAccount.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabAccount_Margin {
            get {
                object obj = ResourceManager.GetObject("tabAccount.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabAccount_Padding {
            get {
                object obj = ResourceManager.GetObject("tabAccount.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1050, Height=618} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size tabAccount_Size {
            get {
                object obj = ResourceManager.GetObject("tabAccount.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tabAccount_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabAccount.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        internal static string tabAccount_Text {
            get {
                return ResourceManager.GetString("tabAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle tabControl1_Dock {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point tabControl1_Location {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabControl1_Margin {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1058, Height=658} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size tabControl1_Size {
            get {
                object obj = ResourceManager.GetObject("tabControl1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 8 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tabControl1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabControl1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool tabForecast_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("tabForecast.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=4,Y=24} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point tabForecast_Location {
            get {
                object obj = ResourceManager.GetObject("tabForecast.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabForecast_Margin {
            get {
                object obj = ResourceManager.GetObject("tabForecast.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabForecast_Padding {
            get {
                object obj = ResourceManager.GetObject("tabForecast.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1050, Height=630} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size tabForecast_Size {
            get {
                object obj = ResourceManager.GetObject("tabForecast.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tabForecast_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabForecast.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Forecast 的當地語系化字串。
        /// </summary>
        internal static string tabForecast_Text {
            get {
                return ResourceManager.GetString("tabForecast.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True 的類型 System.Boolean 當地語系化資源。
        /// </summary>
        internal static bool tabHome_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("tabHome.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=4,Y=24} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point tabHome_Location {
            get {
                object obj = ResourceManager.GetObject("tabHome.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabHome_Margin {
            get {
                object obj = ResourceManager.GetObject("tabHome.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding tabHome_Padding {
            get {
                object obj = ResourceManager.GetObject("tabHome.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=1050, Height=630} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size tabHome_Size {
            get {
                object obj = ResourceManager.GetObject("tabHome.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int tabHome_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabHome.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        internal static string tabHome_Text {
            get {
                return ResourceManager.GetString("tabHome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=121,Y=4} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point textRefreshForecastPeriod_Location {
            get {
                object obj = ResourceManager.GetObject("textRefreshForecastPeriod.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding textRefreshForecastPeriod_Margin {
            get {
                object obj = ResourceManager.GetObject("textRefreshForecastPeriod.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=27, Height=23} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size textRefreshForecastPeriod_Size {
            get {
                object obj = ResourceManager.GetObject("textRefreshForecastPeriod.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int textRefreshForecastPeriod_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textRefreshForecastPeriod.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 12 的當地語系化字串。
        /// </summary>
        internal static string textRefreshForecastPeriod_Text {
            get {
                return ResourceManager.GetString("textRefreshForecastPeriod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Center 的類型 System.Windows.Forms.HorizontalAlignment 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment textRefreshForecastPeriod_TextAlign {
            get {
                object obj = ResourceManager.GetObject("textRefreshForecastPeriod.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=50, Height=20} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size ToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("ToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Tools 的當地語系化字串。
        /// </summary>
        internal static string ToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("ToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=67, Height=22} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size traditionalChineseToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("traditionalChineseToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill 的類型 System.Windows.Forms.DockStyle 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.DockStyle treeView1_Dock {
            get {
                object obj = ResourceManager.GetObject("treeView1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {X=0,Y=0} 的類型 System.Drawing.Point 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Point treeView1_Location {
            get {
                object obj = ResourceManager.GetObject("treeView1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Left=4,Top=4,Right=4,Bottom=4} 的類型 System.Windows.Forms.Padding 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.Padding treeView1_Margin {
            get {
                object obj = ResourceManager.GetObject("treeView1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 TreeNode: Home 的類型 System.Windows.Forms.TreeNode 當地語系化資源。
        /// </summary>
        internal static System.Windows.Forms.TreeNode treeView1_Nodes {
            get {
                object obj = ResourceManager.GetObject("treeView1.Nodes", resourceCulture);
                return ((System.Windows.Forms.TreeNode)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {Width=218, Height=658} 的類型 System.Drawing.Size 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Size treeView1_Size {
            get {
                object obj = ResourceManager.GetObject("treeView1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 4 的類型 System.Int32 當地語系化資源。
        /// </summary>
        internal static int treeView1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("treeView1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
