version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  hello-world:
    jobs:
      - build
  #integration-tests:
  #  jobs:
  #    - browser-tests
  #    - ui-tests

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\hMoney
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "hMoney.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\hMoney\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "hMoney.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      #- run:
      #    name: "Run Application Tests"
      #    command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run: dotnet test --no-build --logger "trx"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      #- run:
      #    name: "Test the executable"
      #    command: .\bin\Release\net5.0-windows\win10-x64\publish\hMoney.exe 
      - store_artifacts:
          path: .\bin\Release\net5.0-windows\win10-x64\publish\hMoney.exe
      - store_test_results:
          path: tests/TestResults


#  browser-tests:
#    executor:
#      name: win/default
#    steps:
#      - checkout
#      - run:
#          name: Run browser tests
#          command: |
#              cd WebBrowserTestsSample/tests/WebBrowserTests
#              dotnet test
#  ui-tests:
#    executor:
#      name: win/default
#      shell: powershell.exe
#    steps:
#      - checkout
#      - run: choco install winappdriver
#      - run: 
#          name: Run winappdriver in background
#          background: true
#          command: | 
#              cd "C:\Program Files (x86)\Windows Application Driver\"
#              Start-Process -FilePath "WinAppDriver.exe" -Wait
#      - run:
#          name: Restore and build
#          command: |
#            cd NotepadTest
#            nuget restore
#            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\msbuild\current\bin\"
#            .\msbuild.exe "C:\Users\circleci\project\hMoneyTests\hMoneyTests.csproj"
#      - run: 
#          name: Run UI tests
#          command: |
#              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
#              .\vstest.console.exe C:\Users\circleci\project\hMoneyTests\bin\debug\hMoneyTests.dll
