name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate-changes:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Sonarqube Begin
        run: | 
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:"dennys" /k:"dennys_hMoney" `
            /d:sonar.login="c70a53862de980131b1c6071a6123ae11e259f6d" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /s:..\SonarQube.Analysis.xml

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test --settings coverlet.runsettings --logger:trx
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Sonarqube end
        run: dotnet sonarscanner end /d:sonar.login="c70a53862de980131b1c6071a6123ae11e259f6d"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    
